<?php
/**
 * ACF поля для страницы "О компании"
 *
 * @package The_Capon
 */

// Регистрируем ACF поля после инициализации ACF
add_action( 'acf/init', 'the_capon_register_about_fields' );

function the_capon_register_about_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_about_page',
			'title'                 => 'Поля страницы "О компании"',
			'fields'                => array(
				array(
					'key'               => 'field_about_first_title',
					'label'             => 'Заголовок первой секции',
					'name'              => 'about_first_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'О нас',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_about_first_bg',
					'label'             => 'Фоновое изображение первой секции',
					'name'              => 'about_first_bg',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 0,
					'min_height'        => 0,
					'min_size'          => 0,
					'max_width'         => 0,
					'max_height'        => 0,
					'max_size'          => 0,
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_about_content_blocks',
					'label'             => 'Блоки контента',
					'name'              => 'about_content_blocks',
					'type'              => 'repeater',
					'instructions'      => 'Добавьте блоки контента для страницы',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_about_block_sidebar_title',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => 'Добавить блок',
					'sub_fields'        => array(
						array(
							'key'               => 'field_about_block_sidebar_title',
							'label'             => 'Заголовок сайдбара',
							'name'              => 'sidebar_title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_about_block_sidebar_text',
							'label'             => 'Текст сайдбара',
							'name'              => 'sidebar_text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_about_block_main_text',
							'label'             => 'Основной текст',
							'name'              => 'main_text',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => 4,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_about_block_images',
							'label'             => 'Изображения',
							'name'              => 'images',
							'type'              => 'gallery',
							'instructions'      => 'Добавьте изображения для блока',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'insert'            => 'append',
							'library'           => 'all',
							'min'               => 0,
							'max'               => 0,
							'min_width'         => 0,
							'min_height'        => 0,
							'min_size'          => 0,
							'max_width'         => 0,
							'max_height'        => 0,
							'max_size'          => 0,
							'mime_types'        => '',
						),
					),
				),
				array(
					'key'               => 'field_about_second_media_type',
					'label'             => 'Тип медиа второй секции',
					'name'              => 'about_second_media_type',
					'type'              => 'select',
					'instructions'      => 'Выберите тип медиа для второй секции',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'image' => 'Фоновое изображение',
						'video' => 'Видео MP4',
					),
					'default_value'     => 'image',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_about_second_bg',
					'label'             => 'Фоновое изображение второй секции',
					'name'              => 'about_second_bg',
					'type'              => 'image',
					'instructions'      => 'Используется только если выбран тип медиа "Фоновое изображение".',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 0,
					'min_height'        => 0,
					'min_size'          => 0,
					'max_width'         => 0,
					'max_height'        => 0,
					'max_size'          => 0,
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_about_second_video',
					'label'             => 'Видео MP4 второй секции',
					'name'              => 'about_second_video',
					'type'              => 'file',
					'instructions'      => 'Загрузите видео файл в формате MP4. Используется только если выбран тип медиа "Видео MP4".',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min_size'          => 0,
					'max_size'          => 0,
					'mime_types'        => 'mp4',
				),
				array(
					'key'               => 'field_about_final_text',
					'label'             => 'Финальный текст',
					'name'              => 'about_final_text',
					'type'              => 'textarea',
					'instructions'      => 'Текст для последнего блока контента',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => 4,
					'new_lines'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_template',
						'operator' => '==',
						'value'    => 'page-about.php',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
}
